# Generated by Django 5.1.6 on 2025-03-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0002_alter_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(default='xxxxxResume', max_length=200),
        ),
    ]
